### ISSUE TITLE
Aspect-orientation does not apply to derived attributes

### ISSUE THREAD

**Issue by ahmedvc** [umple/umple#1028]
Try the model below. The aspect code block will be ignored in the generated code.

class Test{
  name= {"Some value"}
  
  before getName{
    //I will be ignored
  }
}

**Comment by TimLethbridge** [comment]
We realize that the injection should be for the get method. It still does not work. Example:

```
class Test{
   firstName;
   lastName;
   fullName= {firstName+lastName}

  
  before getFullName{
    firstName = firstName+ " ";
   }
}
```

**Comment by hugessen** [comment]
The problem is in the way `JavaClassGenerator` is written. It has multiple `if` blocks for different cases when injecting code. This code should be getting sent to the `attribute_GetDerivedCodeInjection` block, but is instead being sent to the `attribute_GetDerived`. This is because the `if` statement around `attribute_GetDerivedCodeInjection` requires the existence of `after` functionality. 

If I add an `after` statement, both the `before` and `after` code are appended. It also works if I use `after` alone, but does not work with `before` alone.
