### ISSUE TITLE
Umple gets into infinite loop with key in a subclass with infinite cycle error

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1084]
The following crashes the compiler. Likely the key check is looking through the infinite superclass chain before the chain itself is detected

```
class Watershed
{
  Integer id;

}

class District
{
  isA District;
  Integer id;
  key{id}
}

```

**Comment by TimLethbridge** [comment]
This bug may also occur if non-direct cycles are present

There may be similar bugs in other cases where we search the inheritance hierarchy. The solution is either to put the cyclical check first before walking the hierarchy, or detecting loops during other walks. Please search for possible other cases. I have noticed Umple getting into an infinite loop and crashing once in a while; this is the first time I have actually identified a failing case.

I want one of this terms UCOSP students to prioritize this please.

**Comment by TimLethbridge** [comment]
One more thought: The ideal solution is still to put the cycle check first.

However, if the above is hard to do, or even if it is not hard, for extra protection in *all* searches when doing analysis, I suggest limiting them with a counter at some reasonable maximum. For example you would never have an inheritance hierarchy of 25 levels, so this would be a very conservative maximum. When starting to search set a variable to 25 and count down at each iteration. If you reach zero, then stop the search. That will prevent infinite loops. 

The depth of most inheritance hierarchies is zero or one. Occasionally a hierarchy of 4 or 5 is found. Legitimate hierarchies higher than 12 are almost unheard of. Double that to 25 to get a safe search limit.

**Comment by vahdat-ab** [comment]
This is probably related to the issue #449.
Check the method `private void analyzeKey(Token keyToken, UmpleClass aClass)` in class `UmpleInternalParser`, file `UmpleInternalParser_CodeClass.ump`.
Look for the comment `//Issue #449` and investigate the while loop.

**Comment by TimLethbridge** [comment]
I notice you say in your log that you check for cycles every time a token is parsed. I trust that you have taken account of efficiency and that this will not have a large impact on that aspect.

Also I notice you say that now this error is perhaps appearing instead of some other errors as this is being detected first. Make sure the other errors still have some way of being tested.

**Comment by JoshuaMcManus** [comment]
I ran 3 builds each using the old code and my new code (2 first/quick, 1 first/quick) and noticed no significant changes in run-times. They all averaged out to be roughly the same time. My tests were not very scientific, but they at least didn't show any immediate increase in compile time.

I had two tests that were failing 

- The first was from: 

```
class Student
{
  isA Proffesor;
}

class Proffesor
{
  isA Student;
}
```

The original code detected the cycle at the first class, but mine detects it in the second class. I changed this to pass since it has no impact to the user either way (both show that there was a cycle detected).

- The second is from: 

`class A{isA A;}trait A{}`

 I ran this input on the current  version of UmpleOnline and noticed that only the duplicated name is thrown as an error, and the dependency cycle is left out. My implementation does the inverse. I'm not sure if this is okay, but I don't feel as if the user is really losing out on any functionality.
