### ISSUE TITLE
API-generated getters and setters don't populate user-specified method body

### ISSUE THREAD

**Issue by hugessen** [umple/umple#1215]
```
class B{
    Boolean foo;
    Boolean setFoo(String data){
     int a;
    }    
    String getFoo(){
     int a;
     System.out.println("This gets executed");
    }  
}
```
Umple automatically generates getters and setters for each variable defined in it. However, the expected behaviour is that the user should be able to override those methods by providing their own definitions. If the overridden methods have no body, a 1009 error is thrown. If the user-generated methods have a body, though, that body should be added to the API-generated methods. Umple attempts to do this, but for some reason the extra code is discarded before the code is outputted.

See #1210 for the issue preceding this

**Comment by hugessen** [comment]
I see why this is happening.

UmpleInternalParser's `analyzeClass()` method analyzes the class, building and returning an UmpleClass based on the token. The resulting UmpleClass is fully built and contains all of the user-generated code. However, the result of `analyzeClass()` is never assigned to anything. The code looks like this:

```
private void analyzeClassToken(Token t, int analysisStep){
    // some code
    else if (t.is("classDefinition"))
    {
      analyzeClass(t);
    }
```

Instead of assigning the output of `analyzeClass()` and using it in the generated code, this code is discarded. I notice that `analyzeClass()` is called and assigned elsewhere, however it only seems to be this one that adds the user-generated code to the API-generated getters/setters.

Any insight on how to approach this would be greatly appreciated. Otherwise, I will continue to look at this myself.

**Comment by vahdat-ab** [comment]
It doesn't matter if the used-defined method has a body or not. In both cases, the warning should be raised and one of them should be removed. Probably user-defined.
Indeed, there is a bug in the generated code for the above Umple code. The system generates both methods, user-defined and auto-generated. This is not a valid output.

**Comment by TimLethbridge** [comment]
Actually @vahdat the most recent PR stops both methods from being generated (you will not see it in Eclipse as that is only rebuild on a release; I will do another soon). There is a setFoo(String) user defined and a setFoo(boolean) - generated for attribute, but that is OK. The getFoo() user-defined method is being suppressed now. However there is no warning.

The code internally makes a distinction ... if a user-defined method that duplicates a generated method has a body, then do one thing; if the user-defined method has no body then do something else.

There are two options: 1) Issue a warning and ignore it (regardless of the fact it has code in it). 2) convert it into either a 'before set/getX' or 'after set/getX'. But in the second case there should probably be a warning anyway because the change to use before/after is relatively trivial.

I am inclined to think that we should issue a warning that says the code is being ignored and that the user should use a before or after statement to inject it, rather than automatically picking one or the other.

**Comment by vahdat-ab** [comment]
I missed the difference in the parameters' type :-)

**Comment by TimLethbridge** [comment]
We have agreed to a simple solution: Issue a warning where there is a code body in a conflicting method (that has the same signature, whether or not there is a body). I suggest simply modifying message 1009, but after 'please use a different method name', just add 'or use the before or after directives to inject code into the generated method'.

However, on examination I noticed some additional quirks

The following code (call it case A): 
```
class B{
    Boolean foo;
    Boolean setFoo(Boolean data){
    } 
}
```
Generates message 1009.

But the following (call it case B)
```
class B{
    Boolean foo;
    Boolean setFoo(boolean data){
    } 
}
``` 
does not, when in fact case B is the actual conflicting method (as Umple's uppercase Boolean primitive is converted to a lowercase boolean in Java). So Case A should *not* actually generate the message , and case B *should*. When testing, please include cases A and B, and a third case that has some other argument such as String. Finally in all three cases, test both with and without bodies.

**Comment by TimLethbridge** [comment]
When working on another issue I have uncovered the following anomalies:
The code:
```
class X {
  a;
  String getA() {x;};
  String getA() {x;};
}
```
Creates error 1009

But if I take out the duplicate getA then error 1009 goes away. 

Also if the attribute (no body) is defined after the method as below:
```
class X {
  String getA() {};
  a;
}
```
No message is displayed, but if the attribute appears before, then the error appears.

Finally there is message 48 that seems to want to be displayed at UmpleInternalParser_Code.ump:136
I can't seem to ever get this to appear.

**Comment by hugessen** [comment]
@TimLethbridge I have a few questions for you regarding your comments above:

Why do you say it should _not_ display a warning in Case A? Shouldn't both Case A and B show the warning? Is there special significance to the uppercase Boolean in Umple as compared to the lowercase?

In your second comment, the reason no warning is thrown with only one `getA() { x; }` is because there is a method body. As discussed above, I will change that so a warning gets thrown even when there is a method body, and instruct the user to use the before/after methods instead.

In your last case, when the variable is declared after the getter, do you want it behave the same as if the order were flipped? I don't think it would be easy to have the interpreter parse the `a;` before the `getA()` but I think there's an easier way. We could check if the method is a getter, and then look ahead to see if its corresponding variable is declared below it. But that seems like it might be out of scope for this issue.

**Comment by hugessen** [comment]
Consider the following code: 
```
class X {
  doThings() {
  }
  doThings() {
    int x;
  }
}
```
As far as I can see, this situation was designed not to throw an error. Instead, it adds the code from the second method into the first _only if_ the first method has no body. See the relevant `if` block at line 2825 of UmpleInternalParser_CodeClass.ump. I think this `if` block should be eliminated, and the above code should throw a 49 "Duplicate method definition" error. 

This change also corrects this issue, #1215, so that a 1009 error is thrown even if the getter/setter has a method body. I will create a PR to this effect and also update the 1009 error message. Feel free to comment on my thinking here.

**Comment by TimLethbridge** [comment]
Yes, your thinking is correct.

**Comment by hugessen** [comment]
@TimLethbridge when creating my pull request I notice a failing test case after removing that block of code. There are a few of these, but they all refer to multiple language implementations.
```
class X {
  m1 () 
  Java{int a;}
  Cpp{}
  Php{}
}

class X {
  m1 () 
  Cpp{int b;}
  Php{int c;}
}
```
This is the same kind of scenario I describe in my comment above, duplicate method implementations where the first method has no body. The code I removed checks for this case and appends the second method body into the first. 

However, as also stated above, the output of `analyzeClass()`, which generates this outputted class and code, _is never assigned anywhere_.

I'm not familiar enough with Umple to see what the above test case is used for. What is the point of having two definitions of `class X`? Why is there an empty language implementation in one and a code block in the other, especially if that code block is ultimately discarded? Is there an actual use for this?

The test case only fails because now a 49 error is thrown, which is what I was trying to accomplish for this PR. What should I do?

**Comment by TimLethbridge** [comment]
Regarding the last comment:

Having 'two class' X is a fundamental feature of Umple - mixins. It allows bits of classes to be added in different files, allowing or separation of concerns, product lines and so on. 

The code in the test case should be have exactly in the same manner as though the following were present:
```
class X {
  m1 () 
  Java{int a;}
  Cpp{int b;}
  Php{int c;}
}
```

Anyway. An empty body should be a valid body (can be valid, for example in the case of a method that had no return value and is designed to be overridden (a hook); or simply as a temporary placeholder.  The current implementation raises error 49 when two real bodies are defined for a method, but it silently ignore the empty body case. That could be useful to allow a default implementation for a class, and then another implementation for a product version that needs to behave a little differently. I think these tests cases should be made to pass without altering them. The PR needs changing so that the test cases pass.

The original issue had to do explicitly with methods that conflict with generated methods; fixes for the issue should not have an impact on any other methods

**Comment by TimLethbridge** [comment]
I realized I didn't answer an earlier question ' Is there special significance to the uppercase Boolean in Umple as compared to the lowercase?'. In Umple, uppercase Boolean as a type on an attribute means the attribute is to use Umple's primitive Boolean type. This can be converted to different types in different languages. It is converted to boolean in Java (lowercase). But methods are by nature always related to a target and/or generated language, so attribute 

```
Boolean a;
```

would generate method
```
boolean getA(boolean)
```

in Java.

**Comment by TimLethbridge** [comment]
It has been agreed that error 1209 would be raised on any attempt to override generated methods, and that before and after should be used to overide them. PR #1230 took that approach. So we can close
