### ISSUE TITLE
Generated code including association with an abstract class

### ISSUE THREAD

**Issue by gublan24** [umple/umple#1274]
There is erroneous Java code produced of Umple when there is a class having a (not directed) association with an abstract class. 

Example: 
```
class Owner
{
   1 -- 1..* AbstractClass hasOneorMany;   
   // Also, the error occurs for 1 -- 1 AbstractClass hasOne; 
}
class AbstractClass{
  abstract;
}

class RowClass
{
 isA AbstractClass; 
  
}
```
The code above will generate Java code that contains the following erroneous code: 
```
public Owner()
{
  hasOneorMany = new AbstractClass(this);
 //  In Java, an abstract class can not be initialized. 
}
```

**Comment by TimLethbridge** [comment]
The 1 -- 1..* causes the problem because it forces instantiation of AbstractClass. The simplest solution would be to add an error message in this case saying that either the association must be directed -> or else must have a * end.

This is similar in concept to error 20, except that there are other solutions. Suggest adding message 80 to this effect.

**Comment by ZainabAlShowely** [comment]
Partly resolved in branch Issue_1274, but fails testing, as one of the test cases contains a one to n association with an abstract class:
~~~Java
class Teacher {
 1 -- 0..2 Foo myFooss;

 1 -- 1..2 Student myStudentss;
}

class Foo {
  abstract;
}

class Student {
  abstract;
}
~~~
A zero to n association does not cause an issue.
It seems that that a one to n association did not previously generate erroneous code. Should the condition for the error 80 to be triggered be specifically a one to many association? Is it simply because the 1--* association with an abstract class has not been dealt with properly, in terms of code generation?

**Comment by TimLethbridge** [comment]
The 1 end forces an instantiated object to be on the constructor, but you can't instantiate an abstract class (only its subclasses). 

The question asked was "Should the condition for the error 80 to be triggered be specifically a one to many association". Actually that is not a well-phrased question, nor is the phase 'zero to n association'. In both cases the 'to' normally refers to the opposite ends of the association, when what you mean is 'zero to n multiplicity' and 'one to many multiplicity'.

Note that an association 1 -- 3..* will also cause this problem.

So the condition for error 80 should be association where both sides have a multiplicity with lower bound greater than zero and one end refers to an abstract class.

**Comment by ZainabAlShowely** [comment]
I see! Yes, I hadn't properly enunciated the associations/ends of associations in question...
OK, I'll modify the condition.
