### ISSUE TITLE
Incorrect Exception Handling Java Code Generation

### ISSUE THREAD

**Issue by DevCon99** [umple/umple#1341]
Since today (20/7, UTC+12), Umple online (try.umple.org) generates incorrect Java code when faced with the following method

"  public static void main(String[] args) {
    new Room().playScenario();
  }
"

The generated code then contains two lines like the following:

    Thread.currentThread().setUncaughtExceptionHandler(new .Room.UmpleExceptionHandler());
    Thread.setDefaultUncaughtExceptionHandler(new .Room.UmpleExceptionHandler());

and a spurious extra "}" is generated after the main method. 

This worked ~24 hours ago.

A current workaround is to use the code

"  public static void main(String... args) {
    new Room().playScenario();
  }
"
Note the use of "..." instead of the "[]" array notation.

**Comment by TimLethbridge** [comment]
I am unable to reproduce this bug. I entered the following complete model into both the current version of UmpleOnline (and the command-line tool) and also a version that existed 2 days ago. In both cases the result is the same and valid Java is generated, which compiles and executes. Would you mind adding to this issue the complete model, not just the main method. It may well be that the issue is arising from some other aspect of the model.

```
class Room {
  void playScenario() {
    System.out.println("Test if playScenario is called");
  }

}

class X {

  public static void main(String[] args) {
    new Room().playScenario();
  } 

}
```

**Comment by DevCon99** [comment]
It seems the generation of erroneous code is triggered by another factor which I haven't been able to pinpoint yet. I'll be back with more information.

**Comment by TimLethbridge** [comment]
We have reproduced this after you sent confidential code, and I have assigned a developer to fix it.

**Comment by ZainabAlShowely** [comment]
The complete model in the comments above seems to currently cause the issue (erroneous lines are generated in the main) when tested in the live version of UmpleOnline... Using the command line tool, the code compiles properly, but to clarify, should these lines be generated (as well as the following UmpleExceptionHandler class) if a main method is present in a .ump file?
~~~Java
Thread.currentThread().setUncaughtExceptionHandler(new UmpleExceptionHandler());
Thread.setDefaultUncaughtExceptionHandler(new UmpleExceptionHandler());
~~~
The issue seems to currently occur with any code that has the full signature of the Java main method. A class such as this:
~~~Java
class X
{
  public static void main(String[] args) {}
}
~~~

Causes the issue in the live UO.

**Comment by TimLethbridge** [comment]
What's bizarre is that the error has 'Room' in it in the generated code, even though there is no 'Room' class!

As for whether all the exception handling code should be there ... my understanding is that this is being generated so that the debugging code all works properly

**Comment by TimLethbridge** [comment]
Deeper and deeper this issue gets ... thinking like Yoda! I just restarted the Umple internal server (UmpleSync.jar starts in server mode by UmpleOnline so it doesn't have to spend resources restarting the VM ... server mode drastically speeds up UmpleOnline). In any case after restarting the variable injected into the erroneous code is now 'X' instead of 'Room'. So what must be going on must be that some data object in the server must somehow be being kept around from run to run. Perhaps there is a static variable being used somewhere where it shouldn't.

**Comment by TimLethbridge** [comment]
So using the Repository of Docker images I get the following:

udock v.1.27.1
  2 months ago
udock v.1.28.0
  19 days ago
 and
udock 6e90158a1ef7cbec6ac0ddb3e9c1d0991b79dd96
  10 days ago 
 for all -- we get 'new .HelloWorld' but only on the *second* generation by the server which is erroneous. So for definite something is being held over from compile to compile, and it is an old problem. I think the best way to track this down would be to look at what code injects 'new UmpleExceptionHandler()' and see if there is some static variable involvement.

**Comment by ZainabAlShowely** [comment]
In the Java generator at uncaught_exception.ump, there is a static variable representing the main class used to generate the exception handling code. I will see how the logic can be modified to remove the need for a static variable.
