### ISSUE TITLE
Class diagram of the Umple compiler is not directing to the correct javadoc page

### ISSUE THREAD

**Issue by WeiqiMaster** [umple/umple#1541]
The Class diagram of the Umple compiler is directing to the older version of Javadoc page
E.g. Clicking the Position Class in the class diagram will direct to https://cruise.eecs.uottawa.ca/umple/umple-compiler-javadoc/index.html?cruise/umple/compiler/Position.html, which is outdated

**Comment by TimLethbridge** [comment]
To be more specific, the problem is that when certain classes are clicked on in a generated diagram (i.e. from http://metamodel.umple.org) a link URL is being constructed that points to that class as it had existed some years ago when the class was in an previous package, rather than the package where it has been moved. For example 'Point' points to the version of the documentation at cruise/umple/compiler/Position.html rather than at cruise/umple/parser/Position.html

Solutions:

- Remove old documentation when regenerating the diagram
- Change the linking code so it correctly links to the right package
- Currently a Javascript method called Action.selectClass is called with the wrong link from umple-compiler-classDiagram.shtml (and other class diagrams that are generated).  This code has packageName hardcoded to go to cruise/umple/compiler except that it is hardcoded to search for certain vmlClasses in a different package. Ideally, the call to the method should have the package name plus the class name.

**Comment by TimLethbridge** [comment]
The relevant javascript code is in umple-*-classDiagram.shtml in the umplewww directory (which on the server are also copied into the same directory as the user manual)

The Action javascript object is used because all diagrams are generated with Action.selectClass calls with the class name, and for UmpleOnline this is much more sophisticated). If a change is made to add a paclage argument, the same thing would have to be done in scripts/umple_action.js

**Comment by TimLethbridge** [comment]
Here's one way of solving the problem that would not require modifying the diagram generator. Rather than being hard-coded to open certain package directories, the javascript  should first test to see if the file is in the 'compiler' directory, and if so open that. If not, it should search the tree of directories until it finds a matching .html and open that.

**Comment by TimLethbridge** [comment]
I have fixed this by using a php script to look up documentation in packages other than compiler. There will be a pull request that updates some files in umplewww shortly
