### ISSUE TITLE
Nothing seems to be loading after running the latest docker image

### ISSUE THREAD

**Issue by joysgithubrepo** [umple/umple#1578]
Hello, today I pulled the latest version of the Docker image (docker pull umple/umpleonline) and ran it on my laptop running Windows 10. I ran the following command : **docker run --rm -ti -p 8000:80 -v E:\umple2:/var/www/ump/umodel umple/umpleonline**. Then I hit the url : http://localhost:8000/umple.php. The page is opening, which is good. But, then nothing seems to be working. Both the left and right panels on the landing page are not loading. If I try to load an existing class diagram as well, its not working. Am I doing something wrong here? Please advise. Thank you.

**Comment by TimLethbridge** [comment]
@joysgithubrepo This is a known glitch that we should fix soon. I believe it has to do with the php version. However if you reload the page, perhaps twice (e.g using control-r) then it seems to normalize. Let me know if this is the case for you

**Comment by joysgithubrepo** [comment]
@TimLethbridge Thank you. I tried what you advised. But, this is not normalizing the thing. Following is the stderr output. Kindly advice if there is anything else I can try to make it work. FYI, I pulled an image which is very old, but the same issue I experienced.
```
2020-07-03 08:16:11,029 DEBG 'nginx' stderr output:
2020/07/03 08:16:11 [error] 10#10: *13 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function json_decode() in /var/www/scripts/tab_control.php:125
Stack trace:
#0 {main}
  thrown in /var/www/scripts/tab_control.php on line 125" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /scripts/tab_control.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8000", referrer: "http://localhost:8000/umple.php"
```

**Comment by TimLethbridge** [comment]
yes, I know about the  PhP error. There is an outstanding pull request from late 2018 that I have been trying to get to test since then. 

But everybody else who has tried the Docker images have simply been able to 'refresh the browser twice after UmpleOnline loads' and it works like a charm. Please reply saying explicitly that you have refreshed the browser twice after UmpleOnline appears.

 If this is not working for you please let me know a) Your platform (Windows, Linux, Mac), b) which browsers you have tested it on; c) what version of Docker you are using. Also you said you tried an old image. Please give the specific one.

Unfortunately I tend to me months to years behind on some things, and I triage (prioritize) intensely; things with workarounds tend to languish. But I have about 1000 things in my to do list and the pandemic is making things ever more crazy. Also I don't know who you are? Are you a prof or a student? If so what university. If this is for corporate work, what corporation. Feel free to privately email me. I need to know this to help set priorities.

**Comment by joysgithubrepo** [comment]
Thank you. I am running Docker Desktop version 2.3.0.3 which is running Docker version 19.03.8, build afacb8b. I am on Windows 10. I have tested the application using both Internet Explorer, Google Chrome. Please let me know which email address I should use to contact you privately. Thank you.

**Comment by joysgithubrepo** [comment]
Hello @TimLethbridge May I please request you to let me know how to contact you? I can then progress with using UmpleOnline locally. Thank you.

**Comment by TimLethbridge** [comment]
Contact me at timothy.lethbridge@uottawa.ca

**Comment by TimLethbridge** [comment]
This has been fixed
