### ISSUE TITLE
Umple Error compiling Java occurs while using a path whose name contains a space

### ISSUE THREAD

**Issue by 1998Charles** [umple/umple#1603]
There is an Umple Compiling Error when compiling the resultant java code with -c - while using a file whose path contains a space.

<img width="730" alt="Compiling Error" src="https://user-images.githubusercontent.com/60756026/87884753-99e3fe80-c9de-11ea-8a63-052e50fd65d4.png">

**Comment by TimLethbridge** [comment]
This is caused by the Java compiler, not the Umple compiler. It is a known issue that has been reported for many products. The classpath for the java compiler cannot be set. I have a pull request ready to warn people to remove spaces from their path. That is the best we can do. In general in Unix-based systems directories with spaces are best to avoid anyway.
