### ISSUE TITLE
It would be useful if the umple command-line compiler would tell users where the main method(s) are located

### ISSUE THREAD

**Issue by 1998Charles** [umple/umple#1604]
If a namespace is specified, as in the following example:

```
namespace microwave;
class Microwave {
  a;
  sm {
     s1 {
       after(1) -> s2;
     }
     s2 {}
  } 
  public static void main(String[] argv) {
    Test t = new Test("aaa");
  }
}
```

and then the user runs

```
java Microwave
```

An error is produced:

```
Error: Could not find or load main class Microwave
Caused by: java.lang.ClassNotFoundException: Microwave
```

**Comment by TimLethbridge** [comment]
This is because the namespace directive causes everything generated to be in a subdirectory. The command line:

```
java microwave/Microwave
```

will work. However, it would be a nice improvement, to avoid this sort of confusion, to add a line after where it says 

```
Success: Processing Microwave.ump
```

to locate the class(s) with the main program(s), if there are any, and to output

```
To run the main program, enter 'java microwave/Microwave'
```
