### ISSUE TITLE
User manual update: Document all the keywords with links

### ISSUE THREAD

**Issue by Nava2** [umple/umple#166]
Originally reported on Google Code with ID 266
Owned by @umple

---

Add a user manual page that lists the Umple Keywords and describes their use, with links
to the correct user manual. There is currently a wiki page that just lists them.

---

Reported by @umple on 2012-01-31 14:58:55

**Comment by Nava2** [comment]
EVerything red in the grammar is a keyword
http://cruise.eecs.uottawa.ca/umple/UmpleGrammar.html

A new program could be written to extract from the grammar just the list of keywords,
so there is always a current keyword list automatically generated. This list should
have links to the relevant grammar rule, and ideally other manual pages containing
references to the keyword. This would require modifying the documentation generator.

---

Reported by @umple on 2012-06-14 20:21:00
- **Labels added**: Diffic-Easy

**Comment by TimLethbridge** [comment]
Some revised suggestions for this.

At this time I don't think we want to automate finding keywords as suggested above.

The manual page should be in the 'Grammar to define umple' section.

The page should have an alphabetical bulleted list of keywords.

Keywords should appear red, and should also have `<a name="isA">isA</a>` so that we can link to the keyword information section from other sections, including the grammar itself.

After the above, each keyword should have a colon and then a 10-40 word description of the keyword. something like `Defines a superclass, or implemented interface, or included trait`. This should be followed by a link like the following `. <a href="isAclause.html"><i>see isA Clause</i></a>. ` pointing to the most relevant manual page. If there isn't a relevant page, then raise an issue. If there is more than one page then list them both/all, so for example, for the isA clause, the page probably should also include the traits top level page.

The list of keywords should omit the following (but it should be mentioned that these are omitted).

- The list of generators in the generate directives (mention that these are in the 'languages supported' page ... give a link)
- The list of code languages in the codelangs directive

**Comment by TimLethbridge** [comment]
This would be very useful and I would be happy to see this drafted. I will check and edit final wording.
