### ISSUE TITLE
Change the label of the downloading option of the source code in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1699]
After discussion, this issue is being changed. The requirement now is merely to a) Add a tooltip to the 'download as a zip' link emphasizing that this is to enable compiling. Also change the link text to say 'files' so it is clearly going to be one file.

## Summary

Within the UmpleOnline, the users can generate code (e.g. Java, C++, etc) based on the models. In a sample scenario, a user can create a large model and generate the source code accordingly. Based on the viewing preference, the user can check the "Show Files in Separate Tabs" or not. If the user checks that box, then the entire source is encapsulated (class for Java source code) in separate tabs, and each encapsulation contains its own code. If the user does not check that box, the source is going to be displayed in one single tab.

The user can also download the source code in his/her local machine by clicking on the "Download the following as a zip file". If the checkbox "Show Files in Separate Tabs" is not checked and the user is interested in all in a single place, the system still downloads the code in separated files.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
2. Under the "Generate" section, select the target programming language as "Java Code".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/118454167-12325380-b6c6-11eb-830d-2b5bd6b2daf0.png)
3. Scroll a bit down and click on the "Download the following as a zip file" URL.
![image](https://user-images.githubusercontent.com/82404135/118462056-4741a480-b6cc-11eb-9a01-abeffb8b7bf9.png)
4. Now, wait for the download to complete. Extract the downloaded file and look at the files inside that zipped folder.
![image](https://user-images.githubusercontent.com/82404135/118462574-d0f17200-b6cc-11eb-8854-0b97a0407bd8.png)

## Expected Feature

If the user has not checked the "Show Files in Separate Tabs" checkbox, the source code should be downloaded as one single file. Therefore, it should be exactly the same as displayed in the source code section.

**Comment by TimLethbridge** [comment]
I disagree very strongly with this. We will not make this change.

The reason is simple: The downloaded Java needs to be compilable and executable. Real Java is always in files where the file name equals the class name. People understand that and that is what they would expect. 

The  approach of viewing all the code as one unit in the browser (rather than separate tabs, which is an option), is primarily for educational and searching purposes. This works fine in the browser, and the user always has the option in the browser so there would be no need to have it in the downloaded file too. In fact, a user still could copy-paste to a text editor if they wanted that.
