### ISSUE TITLE
Direct browser navigation does not make dropdown selections based on the URL in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1703]
## Summary

Within the UmpleOnline, the users can directly use a navigation URL, paste it into the browser, and press ENTER for easy access to a specific example page.  When the user lands into that specific URL, the UML code and the class diagram are displayed according to the example mentioned in the URL ([example](https://try.umple.org/?example=2DShapes)).

But the dropdown values are not selected according to the URL. The example dropdown is selected as "Select Example". For an URL (https://try.umple.org/?example=2DShapes), the example dropdown should be selected with the value "2DShapes".

## Steps to Reproduce

1. Copy the URL (https://try.umple.org/?example=2DShapes), paste it into the browser, press ENTER.
2. Now, under the "Tools" section, the example dropdown is loaded with "Select Example".
![image](https://user-images.githubusercontent.com/82404135/118477476-b626f980-b6dc-11eb-920b-3593df22cc7a.png)

## Expected Feature

The system should show the specific example as a selected value in the dropdown.

**Comment by TimLethbridge** [comment]
This would be a useful enhancement

**Comment by RalphNgassa** [comment]
The latest commit should now ensure the URL example argument selects the appropriate example from the dropdown menu. But, it seems like the feature diagrams' URLs are broken because they don't load any feature diagram, as you can see on the capture below. I think that might explain why feature diagrams are the only diagrams that persist with the issue I am trying to fix.

If that suits you, I will like to fix that too.
![image](https://user-images.githubusercontent.com/71353825/120663993-8e63bf80-c458-11eb-87a7-2a9ae63ad5cd.png)
