### ISSUE TITLE
The generated link to the loaded diagram disappears after a short while

### ISSUE THREAD

**Issue by RalphNgassa** [umple/umple#1741]
Let's say you load a diagram, in this case "Accidents", you'll notice that the link to the "Accidents" diagram will be displayed for a little while and then disappear, and so does the "Restore saved state" message. The capture below has a red circle which shows the space where these links were supposed to appear.  

![image](https://user-images.githubusercontent.com/71353825/121527645-a099ac80-c9c8-11eb-9032-baafedd43734.png)

**Comment by Svetlana154** [comment]
This issue seems to be tied to the way the edits are being counted, which seems to vary depending on browsers (and perhaps even operating systems). On my machine (Windows with a Linux Subsystem), on Chrome, the URL is displayed and becomes hidden properly after an edit to the example, but on FireFox, it glitches in the same way as described in this issue. Looking at when the edits are saved into the history, there is also a significant difference:
- Upon load: both Chrome and Firefox save the file 2 times
- Upon choosing an example: Chrome saves once, while FireFox saves twice
- Upon code edit: Chrome saves once, Firefox saves twice
- Upon model edit: Chrome saves twice, FireFox saves 4 times

**Comment by TimLethbridge** [comment]
Whoa! If there truly are multiple saves, it would be worth trying to figure out why ... doing so could improve performance significantly. I think it might be worth raising that as a separate issue. It would be good to document the method by which you found that out, and showing logs in such an issue. We should also check it out with Edge, Opera and Safari
