### ISSUE TITLE
GraphViz class with traits and methods active does not display the complete diagram in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1753]
## Summary

Within the UmpleOnline, the users can choose a diagram that he/she want to view in certain circumstances. In particular, scenario, when 'Methods' and 'Traits' and "GraphViz Class" are all selected, the system can not display the whole diagram.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> "Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/121878451-b87b7400-ccd9-11eb-86ea-e61305738eab.png)
2. Now, click the "Options" menu item, select "Methods", "Traits" and  "GraphViz Class" and wait for the diagram.
![image](https://user-images.githubusercontent.com/82404135/121878643-f5476b00-ccd9-11eb-9248-0b4abda561c4.png)

The system can not display the whole diagram and it only loads some partial parts.

## Expected Feature

The system should display the complete diagram.

**Comment by TimLethbridge** [comment]
I modified the title and text of this issue because the example shown clearly had methods and traits active, and the issue was not reproducable unless this was the case.

This will need testing with all examples (most examples have the problem), and care to ensure that the base size is not excessive either.

#1754 seems to be a special case of this, where nothing is visble in certain examples
