### ISSUE TITLE
Crash in SQL generation of Association Specializations first manual example

### ISSUE THREAD

**Issue by camargocr** [umple/umple#1767]
There is a compiler error on example of Association Specialization when execute SQL generate; I tested on-line and command line; below, first lines of log errors:

Couldn't read results from the Umple compiler!
java.lang.StackOverflowError
	at cruise.umple.compiler.Multiplicity.parseInt(Umple_CodeAssociation.ump:659)
	at cruise.umple.compiler.Multiplicity.getUpperBound(Umple_CodeAssociation.ump:621)
	at cruise.umple.compiler.AssociationVariable.isOptionalOne(Umple_CodeAssociation.ump:382)
	at cruise.umple.compiler.SqlGenerator.resolvePrimaryKey(Generator_CodeSql.ump:224)
	at cruise.umple.compiler.SqlGenerator.resolvePrimaryKey(Generator_CodeSql.ump:230)
	at cruise.umple.compiler.SqlGenerator.resolvePrimaryKey(Generator_CodeSql.ump:230)

**Comment by TimLethbridge** [comment]
To be specific, this comes from the user manual page
https://cruise.umple.org/umple/AssociationSpecializations.html

that runs the example at
https://cruise.umple.org/umpleonline/?example=manualexamples/assocSpecEx

When fixing this please look at other issues tagged sql such as #1728

**Comment by Svetlana154** [comment]
<p>The StackOverflowError seems to appear in all cases where there are no variables inside the classes. This is because there is no code in the resolvePrimaryKey function in cruise.umple/src/generators/Generator_CodeSql.ump : line 155 that deals with this situation, causing an infinite recursive loop. </p>
<p>For example, let's say we have 3 classes (A, B, C) that all have an association with each other. None of the classes have any variables. Then the following occurs when resolvePrimaryKey() gets called with class A:</p>

1. The program proceeds to the second if statement in the function since there are no key members<br/>
2. There are no variables so it looks for A's associations<br/>
3. It find its associations with B and C and recursively calls resolvePrimaryKey() with the associated classes through a while loop (let's say B first). Side note: The conditions of the while loop state that the result variable needs to be empty and the loop count has not exceeded the number of associations the selected class has. Things are added to the result variable only in the case of existing key members, existing class variables, or after the recursive calls<br/>
4. The program once again skips of key members, class variables, and looks for B's associations <br/>
5. Result is still empty so we proceed to recursively call resolvePrimaryKey with C<br/>
6. Then the program goes on to find C's associations, recursively calls those as result is still empty, and so forth - forming an infinite recursive loop<br/>
