### ISSUE TITLE
Raising warning for when a mixset not found

### ISSUE THREAD

**Issue by gublan24** [umple/Umple#1873]
When mixsets are used but there are no defintions for these mixsets (in any parsed file), there should be a warning. Example: a file has only `use M1;`

**Comment by TimLethbridge** [comment]
Make sure you test with the mixset use specified on the command line as well. If a use statement is not active (because it is in an mixset that is itself not active) I think the warning should not occur. 

This warning will be similar to the error about not finding a file (1510). I suggest using the nearest available number 1509 (or possibly 1511)

**Comment by TimLethbridge** [comment]
Closed by #1896
