### ISSUE TITLE
keywords 'public' and 'priivate' assumed to be datatypes when they are not, hence generating bad code

### ISSUE THREAD

**Issue by Nava2** [umple/umple#211]
Originally reported on Google Code with ID 311
Owned by @sultaneid

---

When specifying access modifier Umple generates duplicate modifiers the default one
which is 'private' and the specified one regardless of its value.

for example: 

class B
    {
      public  id;
    } 

in java will generate:
...
//B Attributes
private public id;
...

in PHP will generate:
...
//B Attributes
private $id; // which is not as specified in Umple 
... 

If Umple doesn't support specifying the value of access modifiers, then Umple shouldn't
generate invalid code. Also the issue should be covered in the error messages.

**What steps will reproduce the problem?**
1. Remove the duplicated access modifier
2. Accommodate changes for other languages (Php,Ruby, C++)

**What is the expected output? What do you see instead?**

The expected output would be 'public id' when used 'public' or only  'private id' instead
of 'private private id'.

For C++, the attributes that are declared with public, they will be included in the
'public:' zone of the class or maybe just injecting a public keyword before the attribute
to keep the structure of code intact.

And I'm assuming for PHP and Ruby a similar solution should be provided.

---

Reported by @sultaneid on 2012-07-06 01:55:12

**Comment by Nava2** [comment]
The key here is to ensure that specialized keywords such as 'public' and 'private' when
encountered as the 'type' are then ignored.

---

Reported by @umple on 2012-12-31 18:14:25
- **Labels added**: Component-Syntax, Diffic-Easy

**Comment by Nava2** [comment]
Reported by @umple on 2014-10-30 18:02:16
- **Labels added**: ucosp

**Comment by fhackett** [comment]
From what I understand, the problem here is that Umple parses the Java access specifier as a type. This is ambiguous, since this is an intersection between Java and Umple syntax.

Since Umple allows specifying native types and passes them through unaltered, it is not technically incorrect to say the type of id is the native type "public". It is however misleading.

Here are some options I can think of after talking with @vahdat-ab:
- special-case "public", "private" and "protected" to not be valid type names, specifying them will be an error
- generate the same invalid code but output a warning indicating what probably happened
- special-case "public", "private", "protected" and try to sensibly compile it into the target language (this seems like it would be confusing, as the point of writing access specifiers is for them to be passed through not processed... and then you would have to make sure it worked in other target languages, etc...)

**Comment by vahdat-ab** [comment]
> special-case "public", "private", "protected" and try to sensibly compile it into the target language (this seems like it would be confusing, as the point of writing access specifiers is for them to be passed through not processed... and then you would have to make sure it worked in other target languages, etc...)

This case might be defined in another way. Since we have a default type for undefined attributes, we may apply it to this issue as well. For example, `public id` can be considered as `public String id` by the Umple compiler. However, I personally think this might not be a good solution. I'm in favor of having an error/warning messsage for this case.
@TimLethbridge  any comment on this!

**Comment by TimLethbridge** [comment]
In Umple the original intent was that we would follow the standard convention that variables are private; therefore we did not anticipate anybody ever specifying public or private, as we will add 'private' anyway. This is very much an edge case. If you say:

```
public String id;
```

Umple currently says -- that must be local language lingo that is merged into Umple code, we will leave it unchanged without bothering to understand it -- in other words it is parsed as 'extra code' with a warning (that can be suppressed).

On the other hand 

```
public id;
```

is neither Umple nor a local language, hence the problem.

I am not in favour of encouraging people to declare variables as public as such variables then escape being subject to constraints and other analyses.

However, if this bug is to be considered legitimate, it might be worth 'special casing' this, and detecting cases where public|private|protected are found as a type and issuing a warning something like:

Attribute {x} is declared as having {public|private|protected} type; this is likely an error. In Umple attributes are private by default, and are Strings if no type is specified.

**Comment by fhackett** [comment]
All right - that seems reasonable.

I'll try and figure out how to add that warning. This should be a good primer on how the compiler works.
