### ISSUE TITLE
Papyrus model generated from umple throws an error when opened in papyrus eclipse plugin

### ISSUE THREAD

**Issue by Nava2** [umple/umple#280]
Originally reported on Google Code with ID 381

---

Steps to reproduce the problem: 
1. Opened 2D shapes example in umple online and saved it as a .ump file
2. Followed directions from https://github.com/umple/umple/wiki/PapyrusGeneration on
how to generate a papyrus diagram.

Expected output:
Being able to drag and drop from the model explorer the diagram elements generated
from Umple.

Instead this is shown:
http://imgur.com/igrYYrx

Note:
Changing this URI http://www.eclipse.org/uml2/4.0.0/UML in model.notation to http://www.eclipse.org/uml2/3.0.0/UML
solved the issue.

I got the same error on Ubuntu 12.04 and OSX 10.8 both with Eclipse Indigo.

---

Reported by `jzamb022` on 2013-03-06 23:51:15

**Comment by Nava2** [comment]
Reported by `jzamb022` on 2013-03-14 21:07:06
- _Attachment: [patch-Zambrano-381-PapyrusGeneration.diff](https://storage.googleapis.com/google-code-attachments/umple/issue-381/comment-1/patch-Zambrano-381-PapyrusGeneration.diff)_

**Comment by Nava2** [comment]
In general this is an example of where the Papyrus generation needs considerable improvement

---

Reported by @umple on 2013-09-12 14:45:31
- **Labels added**: Priority-Low, Component-SemanticsAndGen, Diffic-Med, ucosp
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-17 12:57:15
- **Labels added**: Component-ExternalTool
- **Labels removed**: Component-SemanticsAndGen

**Comment by Nava2** [comment]
Reported by @umple on 2013-09-17 12:57:28
- **Labels added**: Papyrus

**Comment by TimLethbridge** [comment]
This is an old issue, and Papyrus is a moving target. Anyone working on this would need to explore what needs to be done to ensure Umple keeps working with Papyrus

**Comment by yukangyin97** [comment]
> Originally reported on Google Code with ID 381
> 
> Steps to reproduce the problem:
> 
> 1. Opened 2D shapes example in umple online and saved it as a .ump file
> 2. Followed directions from https://github.com/umple/umple/wiki/PapyrusGeneration on
>    how to generate a papyrus diagram.
> 
> Expected output: Being able to drag and drop from the model explorer the diagram elements generated from Umple.
> 
> Instead this is shown: http://imgur.com/igrYYrx
> 
> Note: Changing this URI http://www.eclipse.org/uml2/4.0.0/UML in model.notation to http://www.eclipse.org/uml2/3.0.0/UML solved the issue.
> 
> I got the same error on Ubuntu 12.04 and OSX 10.8 both with Eclipse Indigo.
> 
> Reported by `jzamb022` on 2013-03-06 23:51:15

Hi professor, I followed above steps, but I couldn't reproduce above reported issue...

Regarding the 2D shapes example, I'm able to see different shapes drawn by Papyrus in eclipse, which is shown below:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/44094961/155612446-b435ffd9-1c9b-4845-8b32-169dce75d721.png">

So, I think the problem is we are missing those generalizations and they should be drawn as well. 

Me and @ruizi fixed this issue in https://github.com/umple/umple/pull/1928

With our fix, the final diagram looks as below:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/44094961/155613766-c0d61719-0039-4851-8b55-926962507e8b.png">

**Comment by yukangyin97** [comment]
The root cause of the error was Umple couldn't generate "\<edges\>" tags and children tags nested in the "<edges>" tags.

This bug was fixed by adding an additional step in Papyrus generator code to generate "\<edges\>" tags.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/44094961/166955489-20b2ec9c-3182-41c8-89ef-21a9d0eb44ca.png">
