### ISSUE TITLE
Umpleonline user interface tests

### ISSUE THREAD

**Issue by Nava2** [umple/umple#363]
Originally reported on Google Code with ID 464
Owned by @CraigBryan

---

Create an enhancement to the automated build to run Capybara tests of the UmpleOnline
user interface. This would test both Umpleonline details as well as loading some examples
and testing them

---

Reported by @umple on 2013-12-02 18:06:11

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2014-07-02 18:21:33
- **Owner changed**: @CraigBryan

**Comment by Nava2** [comment]
Reported by @CraigBryan on 2014-07-14 20:06:33
- **Status changed**: `Started`

**Comment by Nava2** [comment]
Added the start of a test suite for umpleonline with revision r4328. It runs on phantomjs,
so it runs headless. A build script was also added. It requires phantomjs, and a few
rubygems (capybara 2.4+, rspec 3.0, and poltergeist 1.5+) to run.

Run "ant -f build.websitetests.xml help" from the build folder for instructions on
the build script.

The tests are broken into features, and not all website features are covered. The help
target in the build script lists the features that are covered.

There are a number of tests that are "pending" These are tests that are planned, but
not fully implemented due yet.

Some tests have been failing on the test server (ie a non-local server). These failures
are likely due to the longer response time associated with a non-local server. 

---

Reported by @CraigBryan on 2014-08-22 16:05:20
- **Status changed**: `Ongoing`

**Comment by TimLethbridge** [comment]
I would like to push to get this finished. Craig Bryan was almost done with it. But it was never activated. He can help but is graduating soon. it would likely be best if this could be activated however after we move from ant to grade #751 so that we only need to run UI tests in relevant cases; this can be handled by dependencies

**Comment by TimLethbridge** [comment]
I think only activate this on travis and make it optional when myenv=local

**Comment by CraigBryan** [comment]
If I remember correctly largest hurdle in enabled this feature is the repeatability of the tests. When this was run on a non-local server, the speed of responses from the server would often make tests fail. I will take some time to look at these tests and figure out what we need to do to move forward.

**Comment by TimLethbridge** [comment]
So the status seems to be that there is an ant script build.websitetests.xml 

and there are tests themselves at umpleonline/testsuite/spec

We need to polish this work so we can activate it in Travis and also convert it to Gradle

**Comment by RalphNgassa** [comment]
After fixing some minor syntax errors present in the script files, I run the tests on both the local and public umpleonline. There were two persistent errors that made the majority of tests to fail:  'uncaught reference error jquery is not defined' error occurring when the test were ran against the local umpleonline and "Request to 'https://cruise.umple.org/umpleonline/umple.php?' failed to reach server, check DNS and/or server status" error when running the tests against the public umpleonline. I happened to found that these were recurrent problems on phantomJS (not fully loading a page or not reaching a server for security reasons). I would've normally tried to fix the issue on phantomJS but given that this headless browser has been  discontinued about 5 years ago, I found it genuine to replace it with another fully-supported headless browser: Chrome headless. 

And after making this modification the public umpleonline error message disappeared unlike its local umpleonline counterpart. Although I can now look out to fixing the remaining failed (still representing 235/275 test being run)

**Comment by TimLethbridge** [comment]
OK. This sounds like good progress. Chrome Headless seems to be a reasonable choice, but in fact we probably should test on two browsers (so Firefox as well) in the end, but start with Chrome.

Once I have got Jenkins set up we should test against the Umple Jenkins server that I will set up, allowing testing any PR before it goes live. We should not be running tests against https://cruise.umple.org/umpleonline/umple.php because it will make the statistics give wrong results (tests will count as real users when they should not). Instead for now use https://cruise.umple.org/test/umpleonline/umple.php

I wonder if some of the tests are failing because UmpleOnline has itself changed since the tests were created? Please check and modify tests if needed.

One more thing: This website may give some tips https://www.guru99.com/selenium-with-htmlunit-driver-phantomjs.html although there are likely to be many other good online sources to help you

Tim
