### ISSUE TITLE
Constraints with == converted to equals() in Java, but failing on primitives

### ISSUE THREAD

**Issue by Nava2** [umple/umple#487]
Originally reported on Google Code with ID 589
Owned by `redeyedmars`

---

In the SecurityLight example (umpleonline/ump/SecurityLight the generated Java  has
a bug where the original constraint has == to compare two booleans, but it has been
changed to generate a call to equals(). But this doesn't work with Booleans

http://cruise.eecs.uottawa.ca/umpleonline/?example=SecurityLight

---

Reported by @umple on 2014-06-09 20:56:58

**Comment by Nava2** [comment]
Reported by @umple on 2014-06-12 13:28:37
- **Owner changed**: `redeyedmars`

**Comment by TimLethbridge** [comment]
This is still a significantly problematic issue.

The bad generated code reads: 

```
case off:
  if (getAmbientLight().equals(false))
```

**Comment by TimLethbridge** [comment]
The issue is that the generator looks to see whether the variables are primitive (e.g. int would use ==), but sees Integer in the umple and says this is not primitive. However, Umple considers Integer an native Umple type and uses int when it generates Java. But the generator does not recognize that this has happened.

**Comment by TimLethbridge** [comment]
Specifically, the following:

```
class X {
 Integer  a;
 Integer b;
  sm {
    s1 {
      m1 [a==b] -> s2;
    }
    s2 {
    }
  }
}
```

generates

```
private int a;
private int b;
...
if (getA().equals(getB())) ... // fails to compile in Java
```
