### ISSUE TITLE
Trying to disable text editor with shortcut opens a new tab

### ISSUE THREAD

**Issue by Nava2** [umple/umple#548]
Originally reported on Google Code with ID 650

---

**What steps will reproduce the problem?**
1. Write any umple code so we can see a diagram
2. Press ctrl+t to hide the text editor

**What is the expected output? What do you see instead?**
Expected: text editor hides.
Actually: a new tab opens.

**What version of the product are you using? On what operating system?**
Latest UmpleOnline, Ubuntu 14.04.

**Please provide any additional information below.**
I am using Chrome Version 38.0.2125.111 (64-bit). Ctrl+t is a Chrome short-cut for
opening a new tab, which interferes with Umple's shortcut.

---

Reported by `gabriel.tapuc` on 2014-11-07 17:17:38

**Comment by TimLethbridge** [comment]
Control-t works fine in Mac OS (on Chrome and other browsers. Keep that. 

Detect OS and make it something else that doesn't conflict on Linux and Windows, (e.g. something else with the 't'). Check the other shortcuts too.

**Comment by Diusrex** [comment]
I can take this issue.

**Comment by vahdat-ab** [comment]
great.

**Comment by TimLethbridge** [comment]
Make sure you leave the key bindings on Mac OS in tact. The key is to use key binding combinations that work on other platforms (e.g. control-option-t) might be a good choice in Windows and Linux instead of (control-t). The latter would still work on Mac. This needs testing in multiple browsers on multiple OSes. And all the key bindings need changing. key bindings are set in two separate places ... one for the text pane and one for the graph pane.

**Comment by Diusrex** [comment]
The two key bindings that failed are control-t and control-n. It looks like this issue isn't because of Windows/Linux since it works in Firefox for both Windows and Linux. Instead, it fails in Google Chrome because the two key bindings are reserved.

For control-n, I was able to get it working as control-alt (option)-t in both Windows and Linux. However, while I was able to get ctrl-alt-t working in Windows, in Linux (Ubuntu) it will open a terminal rather than be captured by the javascript.

**Comment by Nava2** [comment]
I feel like working with `ctrl + t` or `cmd + t` is just a bad idea. This shortcut is commonly used in many applications. What about using `cmd + h` or `ctrl + h`. It'd take some research to confirm, but I don't think those key shortcuts are used. It'd take some investigation, but I feel like using `t` is just too common and will run into problems. 

This is horrendous to look at, but should prove useful: [Keyboard Comparison](http://dmcritchie.mvps.org/firefox/keyboard.htm).

Obviously, this is just my opinion, your mileage may vary.

**Comment by TimLethbridge** [comment]
I would prefer to leave the 't' for text. Yes, lots of apps use t, but for many different purposes.

**Comment by Diusrex** [comment]
Because of `ctrl + alt + t` opening the terminal in Ubuntu, and `ctrl + shift + t` also being reserved in Chrome, would need to use `ctrl + alt + shift + t` in Ubuntu for Chrome (or not use t).

`ctrl + h` doesn't work in Chrome because it is reserved for history, but `ctrl + alt + h` works for Windows and Ubuntu.

**Comment by TimLethbridge** [comment]
I suggest using ctrl on the Mac and ctrl alt shift for the others. Hiding the diagram with ctrl-d or command-d on the mac will be much more of a common operation than hiding the text. And as long as the tooltip appears correct, all should work.

**Comment by Diusrex** [comment]
Which tooltip are you referring to? I understand there is the tooltip for diagrams, but I haven't seen any 
related to the shortcuts.

Also, should I create a user manual page for all of the shortcuts by OS?

**Comment by TimLethbridge** [comment]
All the commands operable by keyboard shortcuts have menu items. So go to options menu and hover over each menu item, and you will see the various tooltips with the d t a m e g s keys. 

You are right, The webpage http://cruise.eecs.uottawa.ca/umple/UsingUmpleOnline.html should be updated to include the key bindings. Inputs to the manual are in build/reference
The manual is built using ant -Dmyenv=local -f build.umple.xml packageDocs
