### ISSUE TITLE
Association name ending in 's' generates inconsistent method names

### ISSUE THREAD

**Issue by Nava2** [umple/umple#556]
Originally reported on Google Code with ID 658

---

The following Umple snippet ...

class Qx {}
class Xs {}

association { \* Qx qx -- \* Xs xs; }

... generates the following code in class Qx (in Java):

  private List<Xs> xs;

  public Xs getX(int index)
  {
    Xs aX = xs.get(index);
    return aX;
  }

You would expect the following instead:

  public Xs getXs(int index)
  {
    Xs aX = xs.get(index);
    return aX;
  }

It appears the translator strips off the trailing s when generating methods that are
considered singular as opposed to plural. Also, this appears to be independent of the
multiplicities in question. 

---

Reported by `alexwithaneye` on 2014-12-04 00:34:05

**Comment by TimLethbridge** [comment]
The problem seems to be for two-letter classes that end in 's'. =Class names should be singular so this case will be rare. However in cases where a singular class name ends in 's'  and the class is more than two letters long all seems fine. The following code generates OK, so I am closing this issue.
class Pass {
}
