### ISSUE TITLE
Using immutable key generates invalid Java code

### ISSUE THREAD

**Issue by Nava2** [umple/umple#594]
Originally reported on Google Code with ID 696

---

**What steps will reproduce the problem?**
1. http://cruise.eecs.uottawa.ca/umpleonline/umple.php?model=150401739102
2. Generate Java code, view hashcode() method, "canSetK" is used however does not exist

**What is the expected output? What do you see instead?**

"canSetK" should not be used.

---

Reported by @Nava2 on 2015-04-01 21:24:13

**Comment by TimLethbridge** [comment]
This issue is not fixed. 
File cruise.umple/src-gen-jet/cruise/umple/compiler/java/JavaClassGenerator.java
should have the fix in it. That never happened. In a full build the

**Comment by toulayha** [comment]
Hi Tim
The change I made was in the “UmpleToJava/templates/equals.jet” which changes both the "UmpleToJava/src/cruise/umple/compiler/java/JavaClassGenerator.java” and "cruise.umple/src-gen-jet/cruise/umple/compiler/java/JavaClassGenerator.java” from what is resulting in my machine after doing a full build using "ant -Dmyenv=local”.

I have just done a full build again now and the test I added is passing in eclipse just like it did before I made the pull request. 
I have also done diff between the JavaClassGenerator.java files and they were identical except for this, which makes sense:
diff cruise.umple/src-gen-jet/cruise/umple/compiler/java/JavaClassGenerator.java UmpleToJava/src/cruise/umple/compiler/java/JavaClassGenerator.java
21c21

## <   protected final String TEXT_1 = "/_PLEASE DO NOT EDIT THIS CODE_/" + NL + "/_This code was generated using the UMPLE ${last.version} modeling language!_/";

>   protected final String TEXT_1 = "/_PLEASE DO NOT EDIT THIS CODE_/" + NL + "/_This code was generated using the UMPLE @UMPLE_VERSION@ modeling language!_/“;
> I have tried an example after the full build and it is still working fine.

I have also done a find for “fail” and These are the two things failing:
[junit] TEST cruise.queued.statemachine.test.MultipleQueuedStateMachinesTest FAILED
    [junit] Tests FAILED

```
[junit] WARNING: multiple versions of ant detected in path for junit 
[junit]          jar:file:/usr/local/apache-ant/lib/ant.jar!/org/apache/tools/ant/Project.class
[junit]      and jar:file:/Users/aymenbenrkhis/Dropbox/Fall/CSCI%204191%20-%20Application%20Dev%20Project/UCOSP/code/umple/dist/libs/core/ant.jar!/org/apache/tools/ant/Project.class
[junit] Tests FAILED (crashed)
```

The latter has been there since I did the set up and have been using eclipse to test.
