### ISSUE TITLE
Download links on the 'Umple Tools' userdoc page are out of date

### ISSUE THREAD

**Issue by Nava2** [umple/umple#604]
Originally reported on Google Code with ID 706
Owned by @umple

---

http://cruise.eecs.uottawa.ca/umple/UmpleTools.html

**What is the expected output? What do you see instead?**
They link to: https://code.google.com/p/umple/downloads/list
but they should probably link to: https://github.com/umple/Umple/releases/tag/v.1.22.0.5146
-or-
http://try.umple.org/scripts/umple.jar

**Please use labels and text to provide additional information.**

---

Reported by `jzwiep` on 2015-04-13 04:43:47

**Comment by TimLethbridge** [comment]
Link on Umpleonline is also out of date. Search throughout.

**Comment by TimLethbridge** [comment]
Actually I am going to ask you to change the links you made. They should link to
https://github.com/umple/umple/releases
so that the links are always up to date with the latest release.

However in analyzing this issue, I find a bunch more references to Google in the documentation:
do 
grep google *
in build/reference to find the others

And this time please do a Pull Request, and don't push the commits directly to master.

**Comment by toulayha** [comment]
Hi Tim

I have updated the link to the one you sent, and updated the ones under build reference as well.
There is a problem, however, with this page http://cruise.eecs.uottawa.ca/umple/UsingUmpleOnline.html http://cruise.eecs.uottawa.ca/umple/UsingUmpleOnline.html. Loading an example using url from github does not work just like the old google code links. I still updated the links to github, though. I can look more into, if you do not know why is that happening.

Concerning pull requests, I am quite confused. So after committing my changes, should I just make a pull request without pushing them ?  Because that is what I did now and the changes are not appearing on my github. Could you please clarify how the process works ?

Thanks
Aymen

**Comment by Nava2** [comment]
Hi Aymen,

Your code is currently in your branch. Your commits are being seen here
since you've tagged the issue, e.g. #604. You'll need to create a pull
request from your repository to merge into the main one. It can then be
reviewed by Tim/Andrew. I'm on mobile, but look up githubs tutorial on
making a pull request for more information.

**Comment by TimLethbridge** [comment]
Hi Aymen,

I am broadening the discussion so that everybody on umple-dev sees this.

Kevin has given you some tips as to how to make a pull-request work for you. I am also new to git, so I am going to ask him or andrew to guide you through the process.

As for updating the user manual (issue 604). The problem you were having with the ‘filename=‘ options to UmpleOnline are that in GitHub all proper requests must use https:// and the filename option was only using http:// I just fixed umpleonline so it will try https too.

Also some of the pages have moved in the hierarchy

As such a page in the manual that linked to a specific file in Google code such as
http://cruise.site.uottawa.ca/umpleonline/?filename=umple.googlecode.com/svn/trunk/cruise.umple/test/data/InventoryAndOrders/ClientOrder/MailOrderSystemClientOrder.ump http://cruise.site.uottawa.ca/umpleonline/?filename=umple.googlecode.com/svn/trunk/cruise.umple/test/data/InventoryAndOrders/ClientOrder/MailOrderSystemClientOrder.ump

can now be rewritten as

http://cruise.site.uottawa.ca/umpleonline/?filename=raw.githubusercontent.com/umple/umpleonline/ump/MailOrderSystemClientOrder.ump http://cruise.site.uottawa.ca/umpleonline/?filename=raw.githubusercontent.com/umple/umpleonline/ump/MailOrderSystemClientOrder.ump

> On Oct 10, 2015, at 00:33, Aymen Ben Rkhis notifications@github.com wrote:
> 
> Hi Tim
> 
> I have updated the link to the one you sent, and updated the ones under build reference as well.
> There is a problem, however, with this page http://cruise.eecs.uottawa.ca/umple/UsingUmpleOnline.html http://cruise.eecs.uottawa.ca/umple/UsingUmpleOnline.html. Loading an example using url from github does not work just like the old google code links. I still updated the links to github, though. I can look more into, if you do not know why is that happening.
> 
> Concerning pull requests, I am quite confused. So after committing my changes, should I just make a pull request without pushing them ? Because that is what I did now and the changes are not appearing on my github. Could you please clarify how the process works ?
> 
> Thanks
> Aymen
> 
> > On Oct 9, 2015, at 5:54 PM, TCLethbridge notifications@github.com wrote:
> > 
> > Actually I am going to ask you to change the links you made. They should link to
> > https://github.com/umple/umple/releases https://github.com/umple/umple/releases
> > so that the links are always up to date with the latest release.
> > 
> > However in analyzing this issue, I find a bunch more references to Google in the documentation:
> > do 
> > grep google *
> > in build/reference to find the others
> > 
> > And this time please do a Pull Request, and don't push the commits directly to master.
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/umple/umple/issues/604#issuecomment-146983719.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/umple/umple/issues/604#issuecomment-147036913.

Timothy C. Lethbridge, PhD, P.Eng., I.S.P., CSDP
Professor of Software Engineering and Computer Science
Faculté de genie / Faculty of Engineering
Université d'Ottawa / University of Ottawa
Tel: 613-562-5800x6685   Fax: 613-562-5664    Mobile: 613-252-1850
http://www.site.uottawa.ca/~tcl

**Comment by toulayha** [comment]
Hi Kevin

So what you are saying is that I should make the pull request after I commit and before I push.
I have committed my changes for the references of files under build/reference and made a pull request. However, the changes are not appearing on my branch on Github, and I thought that was because I did not push them. 
Could you please tell me more about that? 
In the Git tutorial, it says I should push before I make the request which I did the first time and Tim asked me not to.

Thanks,
Aymen

**Comment by Nava2** [comment]
You gotta push them to your repository. Just not to the main one. You're
close!

**Comment by toulayha** [comment]
Okay, that makes sense. But, I think that is what I am having problems with. The branch under my account is called master under toulayha/umple, which is forked from umple/umple. Does that mean they are the same branch ?
If not, does just doing a “git push” from my terminal push the changes to my repository ?

Sorry for asking so many questions, but I just don’t want to repeat the same thing as last one.
Thanks

**Comment by Nava2** [comment]
Okay, when you fork the repository, you get a separate version of your repository: toulayha/umple which you can do as you please with and have no effect on the "upstream" repository, umple/umple. Now, given this, when you clone from your branch, by default it creates "origin" as your fork. You can push/pull from "origin" all you like and it won't affect the "upstream" repository. 

When you create a Pull Request, you're asking the "upstream" repository to pull your changes from your repository into theirs. 

Enough with explanation, what you need to do: 
1. Create a new branch on your repository: `git checkout -b 604-fix-umple-tools-links`
2. Commit your changes into this branch (this is the same as any other commit)
3. Push your changes to origin/branch: `git push origin 604-fix-umple-tools-links`
4. Open Github, to your page, and create a pull request (I see you already did that)
5. Add an informational message about what your pull request does and why it's needed. Write "Closes #604" into the body text somewhere, this ensures that when the PR is merged, it will auto close the issue. 

If you already committed your changes into master, you can still make a branch:
1. Checkout to master: `git checkout master`
2. Create your new branch: `git checkout -b 604-fix-umple-tools-links`
3. Check `git log` to see that your commit is there
4. Continue from the previous steps: 3)

One thing to note, you should make your commit messages meaningful. This lets someone who finds a bug through `git blame` see why you changed the file and diagnose what went wrong. 

To fix your most recent commit, you can do `git commit --amend`.

**Comment by aforward** [comment]
Tim, this should help clarify the process going forward

https://github.com/umple/umple/pull/632

It's a pull request (PR) that adds a contribute page to the umple
repository which describes how to contribute to the project.

andrew f

On Sat, Oct 10, 2015 at 6:10 PM, Kevin Brightwell notifications@github.com
wrote:

> Okay, when you fork the repository, you get a separate version of your
> repository: toulayha/umple which you can do as you please with and have no
> effect on the "upstream" repository, umple/umple. Now, given this, when you
> clone from your branch, by default it creates "origin" as your fork. You
> can push/pull from "origin" all you like and it won't affect the "upstream"
> repository.
> 
> When you create a Pull Request, you're asking the "upstream" repository to
> pull your changes from your repository into theirs.
> 
> Enough with explanation, what you need to do:
> 1. Create a new branch on your repository: git checkout -b
>    604-fix-umple-tools-links
> 2. Commit your changes into this branch (this is the same as any other
>    commit)
> 3. Push your changes to origin/branch: git push origin
>    604-fix-umple-tools-links
> 4. Open Github, to your page, and create a pull request (I see you
>    already did that)
> 5. Add an informational message about what your pull request does and
>    why it's needed. Write "Closes #604
>    https://github.com/umple/umple/issues/604" into the body text
>    somewhere, this ensures that when the PR is merged, it will auto close the
>    issue.
> 
> If you already committed your changes into master, you can still make a
> branch:
> 1. Checkout to master: git checkout master
> 2. Create your new branch: git checkout -b 604-fix-umple-tools-links
> 3. Check git log to see that your commit is there
> 4. Continue from the previous steps: 3)
> 
> One thing to note, you should make your commit messages meaningful. This
> lets someone who finds a bug through git blame see why you changed the
> file and diagnose what went wrong.
> 
> To fix your most recent commit, you can do git commit --amend.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/umple/umple/issues/604#issuecomment-147129817.

## 

aforward
