### ISSUE TITLE
Exclamation points (negation) in guards is not generating code correctly. 

### ISSUE THREAD

**Issue by Nava2** [umple/umple#607]
Originally reported on Google Code with ID 709

---

There are two issues I've found. The first shows from the following code:

```
class A 
{
  boolean thing;
  sm 
  {
    s1 { e1 [thing] -> s2; }
    s2 { e2 [!thing] -> s1; }
  }
}
```

When any code or diagram (I tested with Java, Graphviz State Diagrams, and State Tables)
is generated from this model, the guard is translated to !!getThing(), which is incorrect.

The next example is shown in the following code:

```
class A {
  boolean thing;

  boolean isGoodToGo(boolean t) {
    return true;
  }

  sm {
    s1 {
      e1 [!isGoodToGo(thing)] -> s2;
    }
    s2 {
      e2 [isGoodToGo(thing)] -> s1;
    }
  }
}
```

When this model generates code, the negated guard is translated to 
`!isGoodToGo!(!!getThing())`, which is invalid code (in Java).

This issue is likely related to work done for issue 656.

---

Reported by @CraigBryan on 2015-04-22 00:58:53

**Comment by TimLethbridge** [comment]
It turns out that the fix to issue 554 (old Google issue 656) was not done correctly. The following code

class A 
{
  boolean thing;
  sm 
  {
    s1 { e1 [thing] -> s2; }
    s2 { e2 [!thing] -> s1; }
  }
}

Has two problems:

a) The guard on e2 generates a double negative in
- All generated code
-  the diagram,
- stateTable

b) The diagram shows 'getThing()' as the guard, when it should always show the same code as in the original Umple. This is a separate problem.

Here we will focus on a.

Tests are wrong too, because they expect the double negative.

If I change the case above to call a method:

class A 
{
  boolean thing;
  sm 
  {
    s1 { e1 [getThing()] -> s2; }
    s2 { e2 [!getThing()] -> s1; }
  }
}

The double negation problem goes away

**Comment by TimLethbridge** [comment]
Here is an additional test case that generates bad code

class A 
{
  boolean thing;
  sm 
  {
    s1 { e1 [getThing(a,b)] -> s2; }
    s2 { e2 [!getThing(a)] -> s1; }
  }
}

In this case e2 generates an extraneous negation, and the arguments for e1 are omitted

**Comment by vahdat-ab** [comment]
@TimLethbridge , I wonder if Amid is working on this issue or not?
I can assign it to Morgan if he's not working.

**Comment by amidzak** [comment]
I am working on it. It is actually done but I'm working on another issue
related to it.

**Comment by vahdat-ab** [comment]
@amidzak  Thanks. since we have some issues with assigning names I just wanted to make sure it's been correctly assigned to you.

**Comment by TimLethbridge** [comment]
Done by amid
