### ISSUE TITLE
UmpleTraitTest false positive

### ISSUE THREAD

**Issue by Nava2** [umple/umple#620]
This code eats the exception and passes the test, instead of failing: 

UmpleTraitTest.java#L1147

``` java
                try {
            uMode.run();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            SampleFileWriter.destroy("traitTest.ump");
            SampleFileWriter.destroy("A.java"); 
        }
```

This catch statement should either throw the current exception or be more specific. This pollutes the logs with many caught exceptions that should have been propagated. Investigation is needed to see the scope that this fix has.

**Comment by vahdat-ab** [comment]
The only issue with the method is that there is no need "e.printStackTrace();" because the umple error or warning codes are checked in the next level.
I'll fix it.

**Comment by Nava2** [comment]
The problem is that the code throws valid exceptions. Why are we just catching these Exceptions and throwing them away? If the exceptions are really not important, why throw them in the first place?

If there are exceptions, it would imply the test failed. If that's not the case, revisiting _why_ these exceptions are thrown seems important.

**Comment by vahdat-ab** [comment]
We don't catch them and through it away. I call this method in the test cases and then check the error code defined for Umple. This exceptions are exactly what we see when we run a wrong code in command line. Therefore, I catch them, but I need to make sure the proper umple error code is produced. Otherwise, we won't be able to check the correctness of error codes because system will fail always.
