### ISSUE TITLE
try.umple.org overloaded, need to be able to load balance on the cloud

### ISSUE THREAD

**Issue by vpetkar** [umple/umple#622]
Documentation for running a webserver for UmpleOnline is incomplete and not updated. The hosted variant has dreadful performance, and makes conducting a class based around it impossible.
I was trying to deploy on my Amazon EC2 on an Ubuntu server and unfortunately the documentation is not enough to do so. The links are also dead for setting up Tomcat and most other parts of the tutorial.

**Comment by aforward** [comment]
We recently switched from GoogleCode to Github, can you point us to dead links so that we can help get you up and running.

**Comment by aforward** [comment]
Here is the link to setting up your own UmpleOnline
https://github.com/umple/umple/wiki/SettingUpLocalUmpleOnlineWebServer

I fixed a link to the Windows instructions for setting up on Apache, but if running on a *nix then the instructions should be there inline.  

I also fixed links to the UIGU component.  Note that this component is optional and I would suggest skipping it until you are comfortable with the other steps above.

**Comment by aforward** [comment]
For setting up on an EC2 instance, here the basic instructions

1) Make sure Java 8 is installed and available.

2) Web Server that supports PHP.  If the apache configurations in the link above are date, please help us to make them better.  NGINX could also be used.  You should be able to load a preconfigured stack with this setup for you.

3) Ensure proper permissions for writing the UMP files to.

Let me know how this goes.

**Comment by vpetkar** [comment]
Great to hear back from you, the links have been fixed as well.

As for umple-online, I have installed Java and the machine is running Ubuntu, with NGINX as the web server. I don't think the issue is with NGINX/PHP as other sites seem to be running without issues. The exact error is given as "Couldn't read results from Umple compiler!" on the bottom of the window.

**Comment by TimLethbridge** [comment]
Hi,

Possible solutions
1. Ensure the web server has permission to write to the ‘ump’ directory under umpleonline.
2. Ensure Java is the latest Java 8
3. Ensure Ruby and PhP 5 are installed.
4. Ensure graphViz is installed

Tim

> On Oct 13, 2015, at 11:17, Ved Petkar notifications@github.com wrote:
> 
> Great to hear back from you, the links have been fixed as well.
> 
> As for umple-online, I have installed Java and the machine is running Ubuntu, with NGINX as the web server. I don't think the issue is with NGINX/PHP as other sites seem to be running without issues. The exact error is given as "Couldn't read results from Umple compiler!" on the bottom of the window.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/umple/umple/issues/622#issuecomment-147746894.

Timothy C. Lethbridge, PhD, P.Eng., I.S.P., CSDP
Professor of Software Engineering and Computer Science
Faculté de genie / Faculty of Engineering
Université d'Ottawa / University of Ottawa
Tel: 613-562-5800x6685   Fax: 613-562-5664    Mobile: 613-252-1850
http://www.site.uottawa.ca/~tcl

**Comment by vpetkar** [comment]
I've installed Java8, Ruby (didn't know it was required), and GraphViz (also didn't know it was required). 
Checked the permissions, everything seems to be fine. 

I think this is a far trivial problem... All I did was git clone the repository and then follow the ant build instructions. Is there a tutorial that needs to be followed prior to the SettingUpLocalUmpleOnlineWebServer tutorial other than building via ANT?

**Comment by TimLethbridge** [comment]
OK. So I have escalated this. What we need to so is to host UmpleOnline in more than one place, such that when people go to http://try.umple.org they are directed to one of the places, by way of load balancing. But if they save their file and come back we need to ensure that their files are properly re-loaded, no matter what instance they find themselves on.

It should be possible to choose to use _any_ cloud service, and provision service when the main server detects excess load. For example one or more DigitalOcean, or Amazon EC2 or Microsoft Azure servers could be used. 

The only code modification required would be 

Upon startup with no 'model=' (saved model) then check load; if high, call the load-balancer, and redirect to the appropriate other instance.

If there is a model= parameter, then (initially) don't use the load balancer because the vast majority of users are not saving their models. Later on, we would need to add logic that would
  i. Redirect to a speclific remote server depending on the model number  
  ii. fetch the model from the master on startup using a remote web service
  iii. save the model back to the master again, so if load balancing is turned off then the file is still safe. We don't want to do this every save however.

**Comment by TimLethbridge** [comment]
@vpetcar This problem has been mostly resolved. There is now a Docker image available (see http://docker.umple.org ) that makes depoyment of Umpleonline in the cloud trivial; anyone running a large class can now use this.

We are also working on dealing with accessing a common file store from multiple servers with issue #1123

We are going to deploy in the end on EC2 or similar cloud service ourselves.

The original http://try.umple.org is also much faster than it used to be, since it now uses an internal server.

I am closing this issue, and deferring the remainder of the concern to #1123 @vpetkar
