### ISSUE TITLE
first build failing

### ISSUE THREAD

**Issue by hjamaan** [umple/umple#643]
Hi,

My first build is failing due to internet connectivity issue (as seen in attached screen shot).

Its seems that the macro "isreachable" is returning false when t testing for connectivity, and I read in the comments that it might return false negatives.

What is the issue exactly? any troubleshooting advice is appreciated

p.s. i tried to turn off my firewall, and i am connected to github (ssh)

<img width="939" alt="screen shot 2015-11-06 at 10 43 56 pm" src="https://cloud.githubusercontent.com/assets/13935108/11013372/ddbd4a76-84d8-11e5-9fd3-64c980089dda.png">

**Comment by Nava2** [comment]
Does it pass if you force it to be online?

**Comment by hjamaan** [comment]
yes, it passes if you enforced the online condition to be true.

My concern is the checking for online connectivity. I am connected, however, this condition fails the build scripts. I am trying to pinpoint the issue here.

My assumption is that its related to the 'isReachable' macro.

**Comment by Nava2** [comment]
This is actually caused because the server, `cruise.eecs.uottawa.ca` does not appear to accept PING requests.

```
$ ping -c 1 -t 5 cruise.eecs.uottawa.ca
PING cruise.eecs.uottawa.ca (137.122.89.92): 56 data bytes

--- cruise.eecs.uottawa.ca ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
```

I do not have time to fix this issue, however, a quick fix is: comment out [these lines](https://github.com/umple/umple/blob/master/build/_template.xml#L79-L80), or pass `-Donline=true` if you know that you are in fact online. 

In order to fix this, the ping command should be replaced with the [`<get>`](https://ant.apache.org/manual/Tasks/get.html) task and piping the error to `/dev/null` on *NIX and `NUL` on windows. The `<get>` performs an HTTP GET which is the same as what any other request will use (Ivy uses HTTP calls to download).
