### ISSUE TITLE
a wrong warnning for two events in a state machine with the same name but different parameters

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#656]
**If the following example is executed,**

```
<//----- Example -----
class A{
    status {
        on{
            turnOff(Integer i) -> off;
            turnOff -> off;         
        }
        off{
            turnOn -> on;   
        }
    }
}
//----- End ----->
```

**There is a warning saying**

> Warning 54 on line 5 of file "test.ump":
> Transition turnOff will be ignored due to a unguarded duplicate event

**This is not valid because the names are the same, but the parameters are different. Therefore, the  must be a valid statemenet.**

**Comment by vahdat-ab** [comment]
another issue from the same source 

```
class A {isA T1;} 
trait T1 { 
    status { 
        on { 
            turnOff(int t)-> off;
            turnOn -> on;
        } 
        off{
            turnOff->off;
            turnon -> on;
        }
    }
}
```

In the generated code, there must be two events turnOff. One with an int parameter and anther one without a parameter.

**Comment by nwam** [comment]
Even after deleting all the occurrences of warning 54, the generated code does not contain overloaded methods. This error is raised twice, ever, and it is in` cruise.umple/src/UmplerInternalParser_CodeStateMachine.ump` :

        if(priorAutoTransitionExists){
          setFailedPosition(subToken.getPosition(), 54, subToken.getValue("event"));
          ignoredTransitions.add(subToken);
        }
        if(unguardedEvents.contains(subToken.getValue("event"))){
          setFailedPosition(subToken.getPosition(), 54, subToken.getValue("event"));
          ignoredTransitions.add(subToken);
        }

I believe that this problem persists after removing these lines is due to the means of which events are retrieved or created in the `analyzeTransition` and `analyzeStandAloneTransition` methods in the same file; they use `getEvent(String s)` and `findOrCreateEvent(eventName)` which can only retrieve the same event on every call. 

I will continue to investigate this.

**Comment by nwam** [comment]
After setting up `UmpleInternalParser_CodeStateMachine.ump` to search and create Events by both name and parameters, I hit another roadblock. The test `eventsWithInconsistentArguments` is now failing because it is not throwing an error for having two events with the same name, but different arguments. This makes sense because Events are now set up to be able to be able to be overloaded. 

This is fine for languages like Java and C++, however for languages like PHP, where overloading is not available, this will not do.

**Comment by nwam** [comment]
Aside from my previous comment, in my fork, the generated (Java) code for the examples at the top of this page still do not include overloaded methods. Only the first Event will generate a method. For example, when generating the first example on this page, `turnOff(Integer i)` gets generated, and `turnOff()` does not.

I still have not replaced all occurrences of `findOrCreateEvent(String)` with the new `findOrCreateEvent(String, List<MethodParameter>)` as this gets pretty difficult in some files where parameter data is not immediately available, but that is the suspected cause of this issue.

**Comment by TimLethbridge** [comment]
After all, I think we made a decision long ago that having events with the same name (one with no arguments and one/some with arguments) should not be allowed because a) We could never make it work in PhP (although state machines are not supported in php); b) It probably provides little or no benefit. So after all this work, I think we ought to abandon and close this issue.

**Comment by vahdat-ab** [comment]
Ok, I'm closing this.
