### ISSUE TITLE
Having two arrows for initial states for concurrent states

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#672]
If the following code is executed, there will be two arrows for initial states in the state machine diagram.

```
class A{
    status{
            status{
                on{
                    turn_off -> off;
                    stop{
                        go_play -> play;    
                    }
                    play{
                        go_stop -> stop;
                        go_pause -> pause;
                    }
                    pause{
                        go_play -> play;
                        go_stop -> stop;
                    }
                }
                off{
                    turn_on -> on;
                }
                ||
                active{
                s1{
                    go_s2 -> s2;
                }
                s2{
                    go_s1 -> s1;
                }
            }
        }
    }
}
```

**Comment by vahdat-ab** [comment]
![screenshot from 2015-12-30 00 47 56](https://cloud.githubusercontent.com/assets/3684908/12046859/48f1ebc8-ae8f-11e5-98f7-1e20d59b78cb.png)

**Comment by vahdat-ab** [comment]
![screenshot from 2015-12-30 00 47 56](https://cloud.githubusercontent.com/assets/3684908/12046929/deda0980-ae90-11e5-9229-460a17984acf.png)

**Comment by TimLethbridge** [comment]
Instead of a start symbol in both active and on, with two arrows both going to S1 and to Stop, there should be a start symbol in status, with an arrow going to s1 and another arrow going to stop, indicating that there will be a split of control. (it would b ideal if we could show the notion of the concurrent region properly, but graphviz seems to have no way to allow this,

This will likely be a very challenging problem requiring a lot of time spent understanding code.

It will also be necessary to find all the other examples of state machines in Umple that have this problem and make sure they are solved. Furthermore it will be necessary to ensure that no other state machines are changed.

The best approach would be to first add a proper set of test cases for state machine diagram drawing so any accidental changes resulting from this do not add new defects.

**Comment by TimLethbridge** [comment]
Here's another simpler example
```
class X {
  sm {
    sma {
      eb -> smc;
    }
    smc {
      region1 {
        sp {
          ea -> sp2;
        }
        sp2 {}
      }
      ||
      region2{}
    }
  }
}
```

**Comment by TimLethbridge** [comment]
The code for this is in Generator_CodeGvStateDiagram.ump

Hint: Generate the gv file from Umple. Then edit the gv file until it is correct; then edit the generator.
