### ISSUE TITLE
Windows Tests Failing: `UmpleImportTest`

### ISSUE THREAD

**Issue by Nava2** [umple/umple#724]
I'm currently trying to get Umple to build with [Appveyor](https://ci.appveyor.com). However, I've found some tests now fail on Windows. I'm not overly experienced with Windows and I'd love any feedback from folks who run a Windows environment. 

The failing test cases: 

```
[junit] Tests run: 20, Failures: 20, Errors: 0, Skipped: 0, Time elapsed: 0.68 sec 
    [junit] TEST cruise.umple.compiler.UmpleImportTest FAILED 
```

I'm fairly confident it's a pathing issue, but I just wanted to ask if anyone knows if it might be a configuration issue. 

Here is some more context: 
- Build log: https://ci.appveyor.com/project/Nava2/umple-fyvfu/build/1.23.0-build-12
- Build log set: https://ci.appveyor.com/project/Nava2/umple-fyvfu/history
- Branch: [f-633-myenv-auto](https://github.com/Nava2/umple/tree/f-633-myenv-auto)
- Configuration for the build is found here: https://github.com/Nava2/umple/blob/f-633-myenv-auto/appveyor.yml

**Comment by ahmedvc** [comment]
I quickly looked at the testcase failures. They fail because of a textual difference between expectedText and actualText.  The difference is related to the new line properties. The expected text new line is "\n", while the actual text new line is "\r\n"
The test files such as ECoreImport_InterfaceWithNamespace.ump always assume that the new line separator is "\n".

To solve this issue, the easy fix is to normalize the expected by replacing the new line "\n" with System.lineSeparator(), or we should update the logic behind the textual difference comparison to ignore newline differences instead of using assertEquals to compare two strings.

**Comment by Nava2** [comment]
Thanks, @ahmedvc. I'll do that later today, I appreciate you looking into
it. I don't have much time.

I think I'll do a grep for any new lines and see what I find.

Kevin

**Comment by vahdat-ab** [comment]
This has been a major issue for a long time in Windows environment. Unfortunately, people used "\n" instead of System.lineSeparator() inside many methods. Once I've tried to get rid of all "\n" but I couldn't because they are really cross cut many classes and it's hard to deal with. Finally, I just fix those issues when I face with and let all new members know about this and not to use "\n".

**Comment by vahdat-ab** [comment]
@Nava2 BTW, I've built the Umple in Windows and I didn't get that failure.
