### ISSUE TITLE
Duplicate methods generated when a class implements an interface and has association

### ISSUE THREAD

**Issue by amidzak** [umple/umple#834]
The example below has an interface that defines one of the methods that are generated by umple when having an association

``` java
interface X{
        boolean addY(Y ay);
}

class XImp{
        isA X;
        0..1 -> * Y; 
}

class Y{
}
```

When code is generated in java, PHP, Or Ruby (and probably other languages), the generated class has two implementation of `add_y(Y a_y)` . In Ruby it is `addy(Y a_y)`.
The generated code for XImp in Java is below:

``` java

public class XImp implements X
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //XImp Associations
  private List<Y> ies;

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public XImp()
  {
    ies = new ArrayList<Y>();
  }

  //------------------------
  // INTERFACE
  //------------------------

  public Y getY(int index)
  {
    Y aY = ies.get(index);
    return aY;
  }

  public List<Y> getIes()
  {
    List<Y> newIes = Collections.unmodifiableList(ies);
    return newIes;
  }

  public int numberOfIes()
  {
    int number = ies.size();
    return number;
  }

  public boolean hasIes()
  {
    boolean has = ies.size() > 0;
    return has;
  }

  public int indexOfY(Y aY)
  {
    int index = ies.indexOf(aY);
    return index;
  }

  public static int minimumNumberOfIes()
  {
    return 0;
  }

  public boolean addY(Y aY)
  {
    boolean wasAdded = false;
    if (ies.contains(aY)) { return false; }
    ies.add(aY);
    wasAdded = true;
    return wasAdded;
  }

  public boolean removeY(Y aY)
  {
    boolean wasRemoved = false;
    if (ies.contains(aY))
    {
      ies.remove(aY);
      wasRemoved = true;
    }
    return wasRemoved;
  }

  public boolean addYAt(Y aY, int index)
  {  
    boolean wasAdded = false;
    if(addY(aY))
    {
      if(index < 0 ) { index = 0; }
      if(index > numberOfIes()) { index = numberOfIes() - 1; }
      ies.remove(aY);
      ies.add(index, aY);
      wasAdded = true;
    }
    return wasAdded;
  }

  public boolean addOrMoveYAt(Y aY, int index)
  {
    boolean wasAdded = false;
    if(ies.contains(aY))
    {
      if(index < 0 ) { index = 0; }
      if(index > numberOfIes()) { index = numberOfIes() - 1; }
      ies.remove(aY);
      ies.add(index, aY);
      wasAdded = true;
    } 
    else 
    {
      wasAdded = addYAt(aY, index);
    }
    return wasAdded;
  }

  public void delete()
  {
    ies.clear();
  }

  @Override
  public boolean addY(Y aY){
          return false;
  }

}
```

**Comment by TimLethbridge** [comment]
Good catch. I suggest you try to fix this to get you used to the process.

**Comment by TimLethbridge** [comment]
This could be a ucosp issue of Amid doesn't do it.

**Comment by amidzak** [comment]
I unassigned myself.
But why Umple should automatically implement methods of the unimplemented methods of the parent interface with just a simple return in the body? Since the generated code is not supposed to be altered this method seems useless to be automatically generated anyway.

**Comment by vahdat-ab** [comment]
The main reason is that we wanted to execute our model in a simple way so we automatically generate some codes.
There must be some warnings related to this issue so modelers can notice this.
On the other hand, we don't have to have some many warnings in our parsing and compiling process. This must be analyzed. @TimLethbridge

**Comment by edmundluong** [comment]
Issue appears to be caused by the `JavaClassGenerator.getCode()` method call, where it calls the `getExtraMethodsCode()` method which generates the code for the interface implementation (see [here](https://github.com/umple/umple/blob/master/UmpleToJava/UmpleTLTemplates/JavaClassGenerator.ump#L132)).

It appears that in `getExtraMethodsCode()`, it doesn't take any already implemented methods in the class in consideration hence why it adds a duplicate method from the interface. 

My proposed solution is to check for existing methods with the same method signature (visibility, return type, parameters) in `class_MethodDeclaration.ump` since there is a similar conditional that checks to see if the method exists already in Java and then decides whether these extra methods should be added. (see [here](https://github.com/umple/umple/blob/master/UmpleToJava/UmpleTLTemplates/class_MethodDeclaration.ump#L9))

The UmpleClass and UmpleModel in the JavaClassGenerator appears to have no knowledge of the generated Attributes/Associations method code and their method signatures. Ideally, I should be able to access this information so I can make the appropriate checks to decide whether the method should be skipped over or not.
