### ISSUE TITLE
Create a Docker installation running UmpleOnline

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#901]
To help people create a local version of UmpleOnline, create a Docker image with UmpleOnline running in it (this would require Java8, php5 and graphviz too to be installed in the image and the nginx web server)

**Comment by edmundluong** [comment]
This would a great addition as it would reduce the number of dependencies that need to be installed on the local system to get UmpleOnline up and running. Docker seems to be the way of the future.

**Comment by fhackett** [comment]
Some interesting reading: [https://www.digitalocean.com/community/tutorials/apache-vs-nginx-practical-considerations](https://www.digitalocean.com/community/tutorials/apache-vs-nginx-practical-considerations)

To summarise, it is claimed that nginx is faster than Apache on static content, but Apache is better at handling dynamic content like the PHP that makes up most of UmpleOnline.

[EDIT after rereading for a bit]
... but comments claim nginx is more stable.

I'll try nginx and report back with whether I agree with them.

**Comment by Nava2** [comment]
nginx is also _much_ easier to configure.

**Comment by fhackett** [comment]
Current plan of action:
- use the image openjdk:8-jre-alpine as a base
- the other dependencies are available on Alpine linux as packages, and Alpine Linux has the advantage of being very small
- ~~run a minimal build in the docker box, extract UmpleOnline and the jars we need then remove all the source~~ this part is not actually the best idea, two alternatives were discussed with @vahdat-ab 
  - we should be able to ship nightly builds as well as have an option to do image builds offline, so there will be a local image build option
  - we should also provide a Dockerfile that installs from our release archives. Should they need to, third-party administrators should be able to easily construct their own variant images without needing a dev environment. (I know this will be a very rare case, but it's negligible extra work and I think it's important to have)
- figure out required extra configuration to get nginx serving UmpleOnline
- all of the above will be scripted inside the Dockerfile and will run whenever needed
- put the image on the Docker hub with appropriate metadata, etc...

**Comment by fhackett** [comment]
@Nava2 I remember reading that as well. I'm about to find out either way :)

**Comment by fhackett** [comment]
I've done some more work on this.

Updates:
- I switched the base image to nginx:alpine after seeing the hundreds of lines of config it took them to install nginx right
- It may amuse @TimLethbridge that zip does not come preinstalled on Alpine Linux (the base image), so I had to install it
- I have a kind-of-working image now. There are some things that don't quite work, I'll have to go through and check/polish. Below are the issues I've found so far:
    - State machine diagrams are broken - given that in the Docker container `which dot` outputs "/usr/bin/dot", I think #1081 strikes again.
    - Javadoc output displays 404 - I think this has to do with a difference between Apache and nginx regarding automatically adding /index.html to directories.
- As a follow up to my original discussion (wrt. local installs and installing from release archives) with @vahdat-ab: I tried making the image, and it turns out the image is really completely independent of where the UmpleOnline files come from (I was worried that depending on its location would make it hard to reuse). I'll just leave a comment describing which line someone should replace in order to use their own copy of UmpleOnline, it turns out a separate Dockerfile isn't needed.
- TODO: integrate the docker build with the Ant scripts, find the most reasonable locations for the various config files

**Comment by TimLethbridge** [comment]
Good progress. I look forward to trying this out. I hope you can come up with simple solutions to the problems you noted.

You say that state machines don't display; what about class diagrams using graphviz? They should work the same way.

By the way; I assume you are incorporating the latest versions of java, dot, php (7), Ruby, etc.

**Comment by fhackett** [comment]
More updates:
- Turns out the JavaDoc issue was a quirk of Alpine's Java package not exposing the javadoc executable. What I said about nginx not looking up index.html by default was true but irrelevant. I fixed the problem with some Dockerfile changes.
- Ant integration is basic but works.
- I've pushed an update to my PR for #1081  that should fix the diagram display issue.
- [TODO] Known issue: containers based on this image will lose all data if they are destroyed. This will be very unhelpful for anyone trying to use this on a server (it will wipe data on upgrade) - the issue will need more investigation as it will likely require changes to UmpleOnline's storage system (storing examples, etc in the same folder as user data breaks any of Docker's data persisting methods as they are all based on bind mounts)
- [TODO] I've looked into distributed storage for Docker and it might be trickier than I thought. I should look in more detail and provide a list of options that seem reasonable.

> You say that state machines don't display; what about class diagrams using graphviz? They should work the same way.

That is correct, nothing except for the JS-based diagrams works.

> By the way; I assume you are incorporating the latest versions of java, dot, php (7), Ruby, etc.

This is mostly true. This work period I took some time to upgrade from php 5.6 to 7, since the original tutorial I based my work on was using 5.6.
I've been using Java 8 from the start, along with the stock version of Graphviz that Alpine ships. Ruby and co. are irrelevant as they are not actual dependencies of UmpleOnline; they are not even present in the Docker image.

**Comment by fhackett** [comment]
Since the image is mostly functional at this point (aside from the above issues and waiting for #1081), you can try it like this assuming you have Docker configured properly on your machine:

```
docker run --rm -ti -p 8000:80 fhackett/umpleonline
```

This will spawn an instance of UmpleOnline listening at localhost:8000. You can then navigate to it in your web browser at `localhost:8000/umple.php`.
`^C` to exit when you're done.

Note: If you want a different port, you can change the 8000 in the command to what you want.

@TimLethbridge I remember you asking for some novice-friendly instructions so here they are - there's loads of things you can do not covered above but for basic usage this is pretty much all one would need to know. Feel free to comment anything that seems odd, problems you ran into, etc...

**Comment by TimLethbridge** [comment]
Fantastic! It works mostly (other than generating gv using dot and see below).

I did merge the PR for 1081. I notice that merge didn't automatically make it into the Docker image. Is that process automatable? In any case can you update this image so it has the fix needed to fully work.

One issue: Internally Umpleonline starts a server with port 5555 (or 5556). The Docker image starts this too and other instances acces it. We will have to resolve that.

**Comment by TimLethbridge** [comment]
Correction to my last post. It seems that the port 5555 internal server connection is not exposed outside of Docker! As a result ignore that point. So all we need is a way to make the docker image be updated whenever there are changes to master ... and then to publish it, ideally in the umple account

**Comment by fhackett** [comment]
Glad that worked out - I'll look into the build automation process. The build is currently mostly-local and running out of my checkout of master - the copy I linked above is manually published. Getting an automatically updated "official" build looks like a logical next step. (and making it umple/umpleonline instead of fhackett/umpleonline)

Maybe we could even make available different release tags of UmpleOnline to avoid pinning everyone to the master branch. Master is ok for your average student, but I'll look into easy ways to automate stable releases so more serious users can have control of their upgrades.

[EDIT: I think I see what needs to be done to get automated updates. This will be interesting and hinges on me being able to get my hands on Travis build artifacts. I'll update next week once I try it.]

**Comment by fhackett** [comment]
@TimLethbridge one afterthought: could you add me to the umple organisation on the Docker hub? My username is the same as here, `fhackett`.

**Comment by TimLethbridge** [comment]
@fhackett .. you are now a member of the umple docker team

**Comment by vahdat-ab** [comment]
Cool. I tried and it works out of the box, except dot which was mentioned.
Thanks @fhackett

**Comment by vahdat-ab** [comment]
BTW, it is fast toooooo :-)

**Comment by fhackett** [comment]
I've managed to get automated publishing of docker images to work. As previously mentioned, it's based on Travis CI and runs as a build (building the image) and post-build (publishing it) step on the Linux build variant. My changes are almost but not quite PR-ready (see question at bottom).

My current strategy is to build and push docker images for all commits. This seems ok because technically the Docker Hub allows an infinite number of tags as long as they are for the same image. The tag for a given commit is its commit hash - one might use it to test a specific branch or prior version of UmpleOnline. I do not expect end users to know or care about these.

If you tag a commit (i.e you make a release), that tagged commit's image will also be tagged with the version number. Large users wanting a stable deployment schedule might use these tags to follow stable releases and upgrade on a schedule that suits them.

If a commit is merged into master, a special tag will be given to the latest master commit called "master". @TimLethbridge requested the ability to control the release of bleeding edge UmpleOnline, maybe conducting manual testing before pushing to a publicly known tag. One could do this by advertising a bleeding-edge UmpleOnline called "nightly" and requiring someone to manually retag "master" to "nightly" once they are satisfied UmpleOnline still works. I can provide an Ant process to do this, but for reference the command is this: `docker tag umple/umpleonline:master umple/umpleonline:nightly`.

There are some remaining considerations regarding what we want to consider "latest", i.e what users get by default. Typically this is simply the latest stable release (easily automatable), but I'm not sure what people want so I'm asking here. The other option would be to tie "latest" to "nightly", but that is not what "latest" usually means.

**Comment by Nava2** [comment]
I think having Travis handle pushing images makes the most sense. Have Travis tag any commit that is merged into master (successful PR completed) tag as nightly. Latest on the other hand would be the most recent release tag used.

In an ideal world, nightly would be literal nightly but since Travis doesn't have timed jobs, we go with merged PRs which is an okay cadance. The pattern I describe here is fairly typical to other projects. 

This is my 2 pennies though, @TimCLethbridge makes the ultimate decision.

**Comment by TimLethbridge** [comment]
OK Here's what we want:

For most ordinary Umple developers, we want them to get.
  a) Every merge to master if no changes to Umpleonline (i.e. only changes to compiler or elsewhere)
  b) Additional merges to master (ones with Umpleonline changes such as php or html) after they are tagged using a command like above. I already have a command to issue on the server to put these into production.
  Can this be automated by using pattern matching on the files changed (i.e. if any changes to umpleonline/... don't release to docker

If this can't be done easily then we will go with the tagging for all releases, and it will have to be triggered periodically by an administrator. But this would be less reliable.

Additionally, it has been suggested that a 'slow' release be created (separate Docker image) 

Please do not use 'nightly' in the tag. Use a word such as 'stable'. We don't do things on a nightly basis. Sometimes there are 6 merges a day. Sometimes 6 merges a month.

**Comment by fhackett** [comment]
@TimLethbridge regarding your request to make publishing conditional on commit content, I think that it's doable but may be more trouble than it's worth. It would be hard, for example, to indicate which builds the script deemed block-worthy and might make Travis's behaviour confusing. If my script started misbehaving it would be hard to notice or debug.

I'm curious what your concerns are. As it is I'm not sure what you're getting at with your requirements.

If the worry is the Docker image lagging behind, we can integrate the "stable" publish step into your UmpleOnline deployment script and the Docker image will never be more out of date than UmpleOnline itself.

If someone needs a bleeding-edge image yesterday, you can just send them a commit-tagged link (it even works on non-master branches, if that were to ever be necessary). Key point is to instruct them to discard it in favour of "latest" once whichever changes are merged in.

> we will go with the tagging for all releases, and it will have to be triggered periodically by an administrator.

I'm not sure what you mean by this, if we did go with this wouldn't it be fully automatic? (except bumping the pre-release version) If you make a release tag on git, it will be mirrored on Docker Hub as soon as Travis catches up. It is also relatively trivial to make "latest" follow the latest release thanks to `umpleversion.last.txt`.


Are there any concerns I missed or things I misunderstood?

**Comment by TimLethbridge** [comment]
OK, I will explain more:

The Java part of Umple is 100% tested by Travis. We can be fully confident that if Travis passes, the Java Jars produced are good. Today, every time the build passes, the Jars are immediately put into production UmpleOnline.

However, the javascript and php in UmpleOnline is not automatically tested by Travis. It is manually tested. Hence what happens how is that the Javascript and PhP for any merged PRs are immediately reflected at the test URL:

http://cruise.eecs.uottawa.ca/umpleonline/test/

But are not immediately reflected at tha main UmpleOnline URL:

http://cruise.eecs.uottawa.ca/umpleonline/ (which is also http://try.umple.org )

The reason is that the there may be bugs in the php or Javascript, we don't want to blow all UmpleOnline users up. There is a private script I run on the server that brings the latter up to date after manual testing.

Now for the Docker image: Ideally it would be the same as the main UmpleInline URL so that people don't have to think about whether they have the most up-to-date code. So they would get the Jars updated immediately, but would have to wait for manual confirmation before they get the Javascript and php updates.

**Comment by fhackett** [comment]
@TimLethbridge thanks for explaining, I was completely unaware of that process. Now your request makes more sense.

**Comment by TimLethbridge** [comment]
After an oral discussion today, here is what would happen if a user does:

```
docker run --rm -ti -p 8000:80 umple/umpleonline
```

They would get the latest, which is the latest merge to master, as built successfully on Travis.

If the user does

```
docker run --rm -ti -p 8000:80 umple/umpleonline:branchname
```

They get the head of that branch, as built by Travis. This will allow developers to test umpleonline before merging a PR to master. The workflow would be for the person doing the merging to always pull that image and test UmpleOnline locally.

If the user wants to obtain a specific release, which are created 2-3 times a year in order to help people who don't want their generated code to change constantly, then they can do

```
docker run --rm -ti -p 8000:80 umple/umpleonline:v.n.n.n
```

where v.n.n.n is the tag in git that reflects the 'latest' at the time of the release.

And they could also, as you indicated pick a specific commit corresponding to a branch as well.

Finally, using their own Dockerhub and an ant script you could 

We won't worry about there being too many images.

**Comment by fhackett** [comment]
I have done a bit more work and have now implemented the specification described by @TimLethbridge.

I would like to highlight an extra feature not included there, which is PR tags. Travis builds pull requests as they would appear post-merge (it executes a merge on the build server then builds the result). The build process will detect this and publish a "preview" build. For example, pull request 123 will be available with the tag "pr-123". This should be even more reliable than pulling the branch head (which is also possible).
